# -*- coding: utf-8 -*-
"""lab 9 pfai lab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hDzjSKvdP0HDFcBpGfY3NbO4ZwrTctxJ
"""

!pip install spacy-transformers
!python -m spacy download en_core_web_sm

import spacy
from transformers import pipeline

nlp = spacy.load("en_core_web_sm")

text = """GeekforGeeks was founded by Sandeep Jain.
Sandeep Jain was a former teacher.
GeeksforGeeks is a computer science portal and offers various courses and articles."""

doc = nlp(text)

ner_pipeline = pipeline("ner", model="dbmdz/bert-large-cased-finetuned-conll03-english")
named_entities = ner_pipeline(text)

relationships = []

for sent in doc.sents:
    for ent in sent.ents:
        if ent.label_ in ["PERSON", "ORG"]:
            for token in sent:
                if token.dep_ in ["attr", "nsubj", "dobj"]:
                    relationships.append((ent.text, token.text))

for entity, relation in relationships:
    print(f"{entity} --> {relation}")